version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/php:7.4

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y unzip
            curl -sS https://getcomposer.org/installer | php
            sudo mv composer.phar /usr/local/bin/composer
            composer install

      - run:
          name: Install rsync
          command: sudo apt-get install -y rsync

      - run:
          name: Copy CodeIgniter Application
          command: cp -r path/to/codeigniter /tmp/codeigniter

      - run:
          name: Deploy CodeIgniter Application
          command: rsync -azvh /tmp/codeigniter/ deployer@fezacloud.com:/var/www/html/public/ci_deploy

